print('⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗ ínformações ⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗')
print('nome:marcela')
print('idade:10anos')
print('cor favorita:roxo e verde agua')
print('melhor amiga(o):mel')
print('tem irmãos?:sim')
print('quantos?:2 irmãos')
print('qual sexo?:menina e menino')
print('qual e o nome deles?:carolina e leonardo')
print('quantos anos o leo tem?: 7 anos ')
print('quantos anos a carol tem?: 2 anos ')
print('qual e o nome dos seus pais:andre (progamador) ludmila (dona de casa)')
print('qual e o seu sobrenome?:macedo pitta')
print('esse e o sobrenome de todas as pesoas da sua familia?:nao minha mae tem um sobrenome diferente')
print('qual e o sobre nome da sua mae?:nogueira de macedo pitta')
print('quantos anos seu pai tem?: 45 ')
print('quantos anos sua mae tem?:44')
print('⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗obrigada por me responder!⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗⁗')