x=input('Digite Algo ')
print('Tem só espaços?', x.isspace())
print('É um número?', x.isnumeric())
print('É alfabético? ', x.isalpha())
print('É alfanumérico? ', x.isalnum())
print('Está em maiúscula? ', x.isupper())
print('Está em minúsculas? ', x.islower())
print('Está capitalizada? ', x.isidentifier())